apiVersion: v2
appVersion: "2.13.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A Python based monitoring and tracking tool for Plex Media Server
home: https://truecharts.org/charts/stable/tautulli
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tautulli.png
keywords:
  - tautulli
  - plex
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: tautulli
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/tautulli
  - https://github.com/Tautulli/Tautulli
type: application
version: 15.0.13
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
