apiVersion: v2
appVersion: "0.12.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: This application runs as a daemon on your download host. It checks for completed downloads and extracts them so Radarr, Lidarr, Sonarr, and Readarr may import them
home: https://truecharts.org/charts/stable/unpackerr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/unpackerr.png
keywords:
  - unpackerr
  - sonarr
  - radarr
  - lidarr
  - readarr
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: unpackerr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/unpackerr
  - https://github.com/davidnewhall/unpackerr
type: application
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
