apiVersion: v2
appVersion: "1.2.3"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Whisper is a general-purpose speech recognition model.
home: https://truecharts.org/charts/stable/whisper-asr-webservice
icon: https://truecharts.org/img/hotlink-ok/chart-icons/whisper-asr-webservice.png
keywords:
  - whisper-asr-webservice
  - machine-learning
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: whisper-asr-webservice
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/whisper-asr-webservice
  - https://github.com/ahmetoner/whisper-asr-webservice
type: application
version: 1.0.18
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: machine-learning
  truecharts.org/SCALE-support: "true"
