apiVersion: v2
appVersion: 5.1.1
kubeVersion: ">=1.16.0-0"
version: 8.2.2
name: redmine
description: Redmine is a flexible project management web application written using Ruby on Rails framework.
type: application
home: https://truecharts.org/charts/stable/redmine
icon: https://truecharts.org/img/hotlink-ok/chart-icons/redmine.png
keywords:
  - project
  - management
  - time
  - tracking
  - ticket
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/redmine
  - https://github.com/redmine/redmine
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/category: productivity
  truecharts.org/SCALE-support: "true"
