apiVersion: v2
appVersion: "latest"
deprecated: false
description: A network load-balancer implementation for Kubernetes using standard routing protocols
home: https://truecharts.org/charts/enterprise/metallb-config
icon: https://truecharts.org/img/hotlink-ok/chart-icons/metallb-config.png
keywords:
  - metallb
  - loadbalancer
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: metallb-config
sources:
  - https://github.com/truecharts/charts/tree/master/charts/enterprise/metallb-config
  - https://github.com/metallb/metallb
  - https://metallb.universe.tf
type: application
version: 3.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: core
  truecharts.org/SCALE-support: "true"
