apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A free, open-source expert system for guided interviews and document assembly.
home: https://truecharts.org/charts/incubator/docassemble
icon: https://truecharts.org/img/hotlink-ok/chart-icons/docassemble.png
keywords:
  - docassemble
  - documentation
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: docassemble
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/docassemble
  - https://github.com/jhpyle/docassemble
type: application
version: 0.0.9
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: documentation
  truecharts.org/SCALE-support: "true"
