apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Enjoy Cura directly in your browser with this easy to use Chart
home: https://truecharts.org/charts/stable/cura-novnc
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cura-novnc.png
keywords:
  - cura-novnc
  - HomeAutomation
  - Productivity
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: cura-novnc
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/cura-novnc
  - https://ultimaker.com/software/ultimaker-cura
type: application
version: 5.0.11
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: HomeAutomation
