apiVersion: v2
appVersion: "2.1.12"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: The open-source core of Pinry, a tiling image board system for people who want to save, tag, and share images, videos and webpages in an easy to skim through format.
home: https://truecharts.org/charts/stable/pinry
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pinry.png
keywords:
  - pinry
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: pinry
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/pinry
  - https://github.com/pinry/pinry/
version: 6.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
