apiVersion: v2
appVersion: "1.8.7"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Commento++ is a free, open source, fast & lightweight comments box that you can embed in your static website instead of Disqus.
home: https://truecharts.org/charts/stable/commento-plusplus
icon: https://truecharts.org/img/hotlink-ok/chart-icons/commento-plusplus.png
keywords:
  - commento
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: commento-plusplus
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/commento-plusplus
  - https://github.com/souramoo/commentoplusplus
version: 8.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
