apiVersion: v2
appVersion: "23.10.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: A dead simple static homepage for your server to keep your services on hand.
home: https://truecharts.org/charts/stable/homer
icon: https://truecharts.org/img/hotlink-ok/chart-icons/homer.png
keywords:
  - homer
  - dashboard
  - launcher
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: homer
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/homer
  - https://github.com/bastienwirtz/homer
version: 6.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
