apiVersion: v2
appVersion: 0.202.9
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.66
description: Turns any MySQL, PostgreSQL, SQL Server, SQLite & MariaDB into a smart-spreadsheet.
home: https://truecharts.org/charts/stable/nocodb
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nocodb.png
keywords:
  - nocodb
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: nocodb
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/nocodb
  - https://github.com/nocodb/nocodb
version: 9.0.14
annotations:
  truecharts.org/category: productivity
  truecharts.org/SCALE-support: "true"
