apiVersion: v2
appVersion: 1.18.1
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.66
description: n8n is an extendable workflow automation tool.
home: https://truecharts.org/charts/stable/n8n
icon: https://truecharts.org/img/hotlink-ok/chart-icons/n8n.png
keywords:
  - workflows
  - automation
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: n8n
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/n8n
  - https://docs.n8n.io/
  - https://github.com/n8n-io/n8n
version: 9.1.32
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
