apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 15.3.1
description: Wallos - Self Hosted Subscription tracker
home: https://truecharts.org/charts/stable/wallos
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wallos.png
keywords:
  - dashboard
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: wallos
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/wallos
  - https://github.com/ellite/Wallos
version: 1.0.3
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
