apiVersion: v2
appVersion: "2.0.15"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Hyperion is an opensource Bias or Ambient Lighting implementation
home: https://truecharts.org/charts/stable/hyperion-ng
icon: https://truecharts.org/img/hotlink-ok/chart-icons/hyperion-ng.png
keywords:
  - hyperion-ng
  - hyperion
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: hyperion-ng
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/hyperion-ng
  - https://github.com/hyperion-project/hyperion.ng
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
