annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Productivity
apiVersion: v2
appVersion: "5.5.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: CryptPad is the Zero Knowledge realtime collaborative editor.
home: https://truecharts.org/charts/incubator/cryptpad
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cryptpad.png
keywords:
  - cryptpad
  - Productivity
  - Security
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: cryptpad
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/cryptpad
  - https://cryptpad.fr/
type: application
version: 4.0.1
