apiVersion: v2
appVersion: "21.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: NZBGet is a Usenet downloader client
home: https://truecharts.org/charts/stable/nzbget
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nzbget.png
keywords:
  - nzbget
  - usenet
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: nzbget
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/nzbget
  - https://nzbget.net/
type: application
version: 15.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
