apiVersion: v2
appVersion: "0.10.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Inventory and organization system built for the Home User.
home: https://truecharts.org/charts/stable/homebox
icon: https://truecharts.org/img/hotlink-ok/chart-icons/homebox.png
keywords:
  - homebox
  - inventory
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: homebox
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/homebox
  - https://github.com/hay-kot/homebox
type: application
version: 3.0.13
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: inventory
  truecharts.org/SCALE-support: "true"
