apiVersion: v2
appVersion: "3.7.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.66
deprecated: false
description: A PHP-based self-hosted URL shortener that can be used to serve shortened URLs under your own custom domain.
home: https://truecharts.org/charts/stable/shlink
icon: https://truecharts.org/img/hotlink-ok/chart-icons/shlink.png
keywords:
  - url
  - shortener
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: shlink
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/shlink
  - https://github.com/shlinkio/shlink
type: application
version: 9.1.1
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: utilities
  truecharts.org/SCALE-support: "true"
