apiVersion: v2
appVersion: "1.5.3"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Apache Guacamole is a clientless remote desktop gateway.
home: https://truecharts.org/charts/stable/guacamole
icon: https://truecharts.org/img/hotlink-ok/chart-icons/guacamole.png
keywords:
  - guacamole
  - remote
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: guacamole
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/guacamole
  - https://github.com/apache/guacamole-client
type: application
version: 10.0.15
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: utilities
  truecharts.org/SCALE-support: "true"
