apiVersion: v2
appVersion: "2.2.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Track your cryptocurrency holdings/portfolio
home: https://truecharts.org/charts/stable/cryptofolio
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cryptofolio.png
keywords:
  - cryptofolio
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: cryptofolio
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/cryptofolio
  - https://github.com/Xtrendence/cryptofolio
version: 9.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
