apiVersion: v2
appVersion: 2.1.2
kubeVersion: ">=1.16.0-0"
version: 13.0.26
name: babybuddy
description: Helps caregivers track sleep, feedings, diaper changes, tummy time and more to learn about and predict baby's needs without (as much) guess work.
type: application
home: https://truecharts.org/charts/stable/babybuddy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/babybuddy.png
keywords:
  - baby
  - buddy
  - tracker
  - parents
  - parenting
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/babybuddy
  - https://github.com/babybuddy/babybuddy
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
