apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Self-hosted Rick Roll chart.
home: https://truecharts.org/charts/stable/rickroll
icon: https://truecharts.org/img/hotlink-ok/chart-icons/rickroll.png
keywords:
  - rickroll
  - media
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: rickroll
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/rickroll
  - https://github.com/modem7/docker-rickroll
type: application
version: 3.0.21
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
