apiVersion: v2
appVersion: "0.21.1155"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: API Support for your favorite torrent trackers.
home: https://truecharts.org/charts/stable/jackett
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jackett.png
keywords:
  - jackett
  - torrent
  - usenet
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: jackett
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/jackett
  - https://github.com/Jackett/Jackett
type: application
version: 16.0.5
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
