apiVersion: v2
appVersion: "2.5.7"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: An Application dashboard and launcher
home: https://truecharts.org/charts/stable/heimdall
icon: https://truecharts.org/img/hotlink-ok/chart-icons/heimdall.png
keywords:
  - heimdall
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: heimdall
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/heimdall
  - https://github.com/linuxserver/Heimdall/
type: application
version: 16.0.11
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: organizers
  truecharts.org/SCALE-support: "true"
