apiVersion: v2
appVersion: "0.9.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Web-based LDAP browser to manage your LDAP server
home: https://truecharts.org/charts/stable/phpldapadmin
icon: https://truecharts.org/img/hotlink-ok/chart-icons/phpldapadmin.png
keywords:
  - phpldapadmin
  - openldap
  - userrights
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: phpldapadmin
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/phpldapadmin
  - https://gitlab.v2.rancher.geohub.space/g3s/i3s/i3s-helm-catalog
type: application
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: management
  truecharts.org/SCALE-support: "true"
