apiVersion: v2
appVersion: "4.4.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: AppDaemon is a loosely coupled, multi-threaded, sandboxed python execution environment for writing automation apps.
home: https://truecharts.org/charts/stable/appdaemon
icon: https://truecharts.org/img/hotlink-ok/chart-icons/appdaemon.png
keywords:
  - appdaemon
  - homeautomation
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
  - email: 20650065+warllo54@users.noreply.github.com
    name: warllo54
    url: truecharts.org
name: appdaemon
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/appdaemon
  - https://github.com/AppDaemon/appdaemon
type: application
version: 13.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: utilities
  truecharts.org/SCALE-support: "true"
