apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: hedgedoc
version: 9.0.21
appVersion: "1.9.9"
description: HedgeDoc lets you create real-time collaborative markdown notes.
type: application
deprecated: false
home: https://truecharts.org/charts/stable/hedgedoc
icon: https://truecharts.org/img/hotlink-ok/chart-icons/hedgedoc.png
keywords:
  - hedgedoc
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/hedgedoc
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: incubator
  truecharts.org/SCALE-support: "true"
