apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: couchpotato
version: 6.0.10
appVersion: "latest"
description: Couchpotato is an automatic NZB and torrent downloader.
type: application
deprecated: false
home: https://truecharts.org/charts/stable/couchpotato
icon: https://truecharts.org/img/hotlink-ok/chart-icons/couchpotato.png
keywords:
  - couchpotato
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/couchpotato
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
    # condition:
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: incubator
  truecharts.org/SCALE-support: "true"
