apiVersion: v2
appVersion: "3.5.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A automatic user invitation system for Plex.
home: https://truecharts.org/charts/stable/wizarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wizarr.png
keywords:
  - wizarr
  - HomeAutomation
  - Tools-Utilities
  - Other
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: wizarr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/wizarr
  - https://github.com/Wizarrrr/wizarr
type: application
version: 3.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: HomeAutomation
  truecharts.org/SCALE-support: "true"
