apiVersion: v2
appVersion: "4.2.9"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: rTorrent and ruTorrent chart.
home: https://truecharts.org/charts/stable/rtorrent-rutorrent
icon: https://truecharts.org/img/hotlink-ok/chart-icons/rtorrent-rutorrent.png
keywords:
  - rutorrent
  - torrent
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: rtorrent-rutorrent
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/rtorrent-rutorrent
  - https://truecharts.org/charts/stable/rtorrent-rutorrent
  - https://github.com/crazy-max/docker-rtorrent-rutorrent
type: application
version: 1.0.1
annotations:
  truecharts.org/category: torrent
  truecharts.org/SCALE-support: "true"
