apiVersion: v2
appVersion: "0.0.6"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 7.0.70
deprecated: false
description: A self-hosted bookmark management tool.
home: https://truecharts.org/charts/stable/servas
icon: https://truecharts.org/img/hotlink-ok/chart-icons/servas.png
keywords:
  - servas
  - bookmarks
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: servas
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/servas
  - https://github.com/beromir/Servas
type: application
version: 0.0.24
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: bookmarks
  truecharts.org/SCALE-support: "true"
