annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Tools-Utilities
apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: SeedSync is a tool to sync the files on a remote Linux server (like your seedbox, for example). It uses LFTP to transfer files fast!
home: https://truecharts.org/charts/stable/seedsync
icon: https://truecharts.org/img/hotlink-ok/chart-icons/seedsync.png
keywords:
  - seedsync
  - Tools-Utilities
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: seedsync
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/seedsync
  - https://github.com/ipsingh06/seedsync
type: application
version: 4.0.11
