apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Control your Dell PowerEdge fans via IPMI
home: https://truecharts.org/charts/stable/dell-idrac-fan-controller
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dell-idrac-fan-controller.png
keywords:
  - iDrac
  - Dell
  - fan-controller
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: dell-idrac-fan-controller
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/dell-idrac-fan-controller
  - https://github.com/tigerblue77/Dell_iDRAC_fan_controller_Docker
type: application
version: 2.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: utilities
  truecharts.org/SCALE-support: "true"
