image:
  repository: tccr.io/truecharts/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:51c4ca9a8213d3f4026bd560e8aa2de365d275d6cd0298eff2ae20671fef34e9

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    enabled: false

portal:
  open:
    enabled: false

operator:
  register: true

certmanager:
  dns01RecursiveNameservers: "1.1.1.1:53,1.0.0.1:53"
  installCRDs: true
  enableCertificateOwnerRef: true

metrics:
  main:
    enabled: false
    type: "podmonitor"
    endpoints:
      - port: main
        interval: 5s
        scrapeTimeout: 5s
        path: /
        honorLabels: false

manifestManager:
  enabled: false
