apiVersion: v2
appVersion: "1.7.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Jellyseerr is a fork of Overseerr with support for Jellyfin and Emby. It can be used to manage requests for your media library.
home: https://truecharts.org/charts/stable/jellyseerr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jellyseerr.png
keywords:
  - jellyseerr
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: jellyseerr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/jellyseerr
  - https://github.com/Fallenbagel/jellyseerr
version: 6.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
