apiVersion: v2
appVersion: "231021"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 7.0.70
description: "PhotoPrism® is a server-based application for browsing, organizing and sharing your personal photo collection"
home: https://truecharts.org/charts/stable/photoprism
icon: https://truecharts.org/img/hotlink-ok/chart-icons/photoprism.png
keywords:
  - photos
  - photoprism
  - pictures
  - sharing
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: photoprism
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/photoprism
  - https://github.com/photoprism/photoprism
version: 16.0.11
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
