apiVersion: v2
appVersion: "1.8.14"
version: 13.0.10
kubeVersion: ">=1.16.0-0"
name: etherpad
description: A real-time collaborative editor scalable to thousands of simultaneous real time users.
type: application
home: https://truecharts.org/charts/stable/etherpad
icon: https://truecharts.org/img/hotlink-ok/chart-icons/etherpad.png
keywords:
  - etherpad
  - editor
  - notepad
  - pad
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/etherpad
  - https://etherpad.org/
  - https://github.com/ether/etherpad-lite
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
