apiVersion: v2
appVersion: "23.11.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Avidemux is a free video editor designed for simple cutting, filtering and encoding tasks.
home: https://truecharts.org/charts/stable/avidemux
icon: https://truecharts.org/img/hotlink-ok/chart-icons/avidemux.png
keywords:
  - media
  - avidemux
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: avidemux
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/avidemux
  - https://github.com/jlesage/docker-avidemux
type: application
version: 5.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
