apiVersion: v2
appVersion: "a78f38c1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: "An automated music downloader for NZB and Torrent, written in Python. It supports SABnzbd, NZBget, Transmission, µTorrent and Blackhole."
home: https://truecharts.org/charts/stable/headphones
icon: https://truecharts.org/img/hotlink-ok/chart-icons/headphones.png
keywords:
  - headphones
  - music
  - downloader
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: headphones
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/headphones
  - https://github.com/linuxserver/docker-headphones
  - https://github.com/rembo10/headphones
type: application
version: 8.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
