apiVersion: v2
appVersion: "4.43.10"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Want a Movie or TV Show on Plex or Emby? Use Ombi!
home: https://truecharts.org/charts/stable/ombi
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ombi.png
keywords:
  - ombi
  - plex
  - emby
  - sonarr
  - radarr
  - couchpotato
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: ombi
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/ombi
  - https://github.com/tidusjar/Ombi
type: application
version: 15.0.15
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
