apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: meshcentral
version: 11.0.15
appVersion: "1.1.16"
description: MeshCentral is a full computer management web site
type: application
deprecated: false
home: https://truecharts.org/charts/stable/meshcentral
icon: https://truecharts.org/img/hotlink-ok/chart-icons/meshcentral.png
keywords:
  - meshcentral
  - teamviewer
  - rdp
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/meshcentral
  - https://github.com/Ylianst/MeshCentral
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: mongodb.enabled
    name: mongodb
    repository: https://deps.truecharts.org/
    version: 6.0.67
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: cloud
  truecharts.org/SCALE-support: "true"
