apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: FUSE file system for reading RAR archives.
home: https://truecharts.org/charts/incubator/rar2fs
icon: https://truecharts.org/img/hotlink-ok/chart-icons/rar2fs.png
keywords:
  - rar2fs
  - archives
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: rar2fs
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/rar2fs
  - https://github.com/zimme/docker-rar2fs
type: application
version: 0.0.2
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: archives
  truecharts.org/SCALE-support: "true"
