apiVersion: v2
appVersion: "2.3.13"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Photoview is a simple and user-friendly photo gallery.
home: https://truecharts.org/charts/stable/photoview
icon: https://truecharts.org/img/hotlink-ok/chart-icons/photoview.png
keywords:
  - photo
  - gallery
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: photoview
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/photoview
  - https://github.com/photoview/photoview
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
