apiVersion: v2
appVersion: "3.12.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A Discord bot that displays live data from Tautulli.
home: https://truecharts.org/charts/stable/tauticord
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tauticord.png
keywords:
  - tauticord
  - tautulli
  - discord
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: tauticord
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/tauticord
  - https://github.com/nwithan8/tauticord
type: application
version: 0.0.20
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: discord
  truecharts.org/SCALE-support: "true"
