apiVersion: v2
appVersion: "1.6.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: "PASTA - Audio and Subtitle Track Changer for Plex"
home: https://truecharts.org/charts/stable/pasta
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pasta.png
keywords:
  - pasta
  - MediaApp-Other
  - Tools-Utilities
  - Other
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: pasta
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/pasta
  - https://github.com/cglatot/pasta
type: application
version: 5.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: MediaApp-Other
