annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Downloaders
apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: aMule is an eMule-like client for the eDonkey and Kademlia networks.
home: https://truecharts.org/charts/stable/amule
icon: https://truecharts.org/img/hotlink-ok/chart-icons/amule.png
keywords:
  - amule
  - Downloaders
  - Productivity
  - Tools-Utilities
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: amule
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/amule
  - https://github.com/t-chab/dockerfiles
type: application
version: 4.0.10
