apiVersion: v2
appVersion: 5.1.3.0
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: iSpy's Agent DVR, a standalone DVR service to manage IP cameras.
home: https://truecharts.org/charts/stable/ispy-agent-dvr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ispy-agent-dvr.png
keywords:
  - dvr
  - ispy
  - agent
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: ispy-agent-dvr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/ispy-agent-dvr
  - https://github.com/doitandbedone/ispyagentdvr-docker
version: 6.0.29
annotations:
  truecharts.org/category: security
  truecharts.org/SCALE-support: "true"
