apiVersion: v2
appVersion: "stable"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A game in which you build and maintain factories.
home: https://truecharts.org/charts/incubator/factorio
icon: https://truecharts.org/img/hotlink-ok/chart-icons/factorio.png
keywords:
  - factorio
  - GameServers
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: factorio
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/factorio
  - https://github.com/factoriotools/factorio-docker
type: application
version: 4.1.7
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: GameServers
  truecharts.org/SCALE-support: "true"
