apiVersion: v2
appVersion: "1.0.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A self-hosted podcast manager to download episodes as soon as they become live.
home: https://truecharts.org/charts/stable/podgrab
icon: https://truecharts.org/img/hotlink-ok/chart-icons/podgrab.png
keywords:
  - podgrab
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: podgrab
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/podgrab
  - https://github.com/akhilrex/podgrab
type: application
version: 14.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: mutlimedia
  truecharts.org/SCALE-support: "true"
