apiVersion: v2
appVersion: "1.20.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Lightweight multiplexer/proxy for Minecraft-Java servers.
home: https://truecharts.org/charts/stable/mc-router
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mc-router.png
keywords:
  - mc-router
  - minecraft
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: mc-router
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/mc-router
  - https://github.com/itzg/mc-router
type: application
version: 1.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: minecraft
  truecharts.org/SCALE-support: "true"
