apiVersion: v2
appVersion: 9.4.1
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Fully configurable Zwave to MQTT gateway and Control Panel using NodeJS and Vue
home: https://truecharts.org/charts/stable/zwavejs2mqtt
icon: https://truecharts.org/img/hotlink-ok/chart-icons/zwavejs2mqtt.png
keywords:
  - zwavejs2mqtt
  - zwave-js
  - z-wave
  - zwave
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: zwavejs2mqtt
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/zwavejs2mqtt
  - https://github.com/zwave-js/zwavejs2mqtt
type: application
version: 16.1.1
annotations:
  truecharts.org/category: tools
  truecharts.org/SCALE-support: "true"
