apiVersion: v2
appVersion: "arkse"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A custom SteamCMD chart that runs ArkSE.
home: https://truecharts.org/charts/stable/arksurvivalevolved
icon: https://truecharts.org/img/hotlink-ok/chart-icons/arksurvivalevolved.png
keywords:
  - arksurvivalevolved
  - arkse
  - GameServers
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: arksurvivalevolved
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/arksurvivalevolved
  - https://github.com/ich777/docker-steamcmd-server/tree/arkse
type: application
version: 4.0.11
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: GameServers
  truecharts.org/SCALE-support: "true"
