apiVersion: v2
appVersion: "18.04.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: A high quality, visual, open source tool to create, design, and edit database files compatible with SQLite
home: https://truecharts.org/charts/stable/sqlitebrowser
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sqlitebrowser.png
keywords:
  - sqlite
  - browser
  - sqlitebrowser
  - database
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: sqlitebrowser
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/sqlitebrowser
  - https://github.com/linuxserver/docker-sqlitebrowser
  - https://sqlitebrowser.org/
type: application
version: 7.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
