apiVersion: v2
appVersion: "11.0.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 9.0.43
deprecated: false
description: Reliable and Performant File Sync and Share Solution
home: https://truecharts.org/charts/stable/seafile
icon: https://truecharts.org/img/hotlink-ok/chart-icons/seafile.png
keywords:
  - seafile
  - files
  - cloud
  - file-storage
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: seafile
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/seafile
  - https://seafile.com
type: application
version: 1.0.14
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: file-storage
  truecharts.org/SCALE-support: "true"
