annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Tools-Utilities
apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Adminer (formerly phpMinAdmin) is a full-featured database management tool written in PHP.
home: https://truecharts.org/charts/stable/adminer
icon: https://truecharts.org/img/hotlink-ok/chart-icons/adminer.png
keywords:
  - adminer
  - Tools-Utilities
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: adminer
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/adminer
  - https://github.com/vrana/adminer
  - http://hub.docker.com/_/adminer/
type: application
version: 5.0.37
