apiVersion: v2
appVersion: 17.0
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.3.5
deprecated: false
description: All-in-one business software. Beautiful. Easy-to-use. CRM, Accounting, PM, HR, Procurement, Point of Sale, MRP, Marketing, etc.
home: https://truecharts.org/charts/stable/odoo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/odoo.png
keywords:
  - odoo
  - crm
  - pm
  - hr
  - accounting
  - mrp
  - marketing
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: odoo
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/odoo
  - https://github.com/odoo/docker
type: application
version: 14.0.18
annotations:
  truecharts.org/category: productivity
  truecharts.org/SCALE-support: "true"
