apiVersion: v2
appVersion: "4.16.4"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.66
description: Weblate is a copylefted libre software web-based continuous localization system
home: https://truecharts.org/charts/stable/weblate
icon: https://truecharts.org/img/hotlink-ok/chart-icons/weblate.png
keywords:
  - translate
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: weblate
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/weblate
  - https://github.com/WeblateOrg/weblate
  - https://github.com/WeblateOrg/docker
  - https://github.com/WeblateOrg/docker-compose
  - https://docs.weblate.org/en/latest/
version: 9.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
