apiVersion: v2
appVersion: "13.8.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 7.0.70
description: A photo gallery software for the web.
home: https://truecharts.org/charts/stable/piwigo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/piwigo.png
keywords:
  - piwigo
  - gallery
  - photo
  - image
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: piwigo
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/piwigo
  - http://piwigo.org/
  - https://github.com/linuxserver/docker-piwigo
type: application
version: 7.0.20
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
