apiVersion: v2
appVersion: "0.7.36"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: WireGuard-based VPN server and egress firewall
home: https://truecharts.org/charts/stable/firezone
icon: https://truecharts.org/img/hotlink-ok/chart-icons/firezone.png
keywords:
  - firezone
  - wireguard
  - vpn
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: firezone
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/firezone
  - https://github.com/firezone/firezone
type: application
version: 0.2.14
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: vpn
  truecharts.org/SCALE-support: "true"
