apiVersion: v2
appVersion: "2.19.3"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Container management made easy
home: https://truecharts.org/charts/stable/portainer
icon: https://truecharts.org/img/hotlink-ok/chart-icons/portainer.png
keywords:
  - portainer
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: portainer
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/portainer
  - https://docs.portainer.io/start/install-ce/server
  - https://docs.portainer.io/start/install/server
version: 5.0.18
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: management
  truecharts.org/SCALE-support: "true"
