apiVersion: v2
appVersion: "4.7.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Flood is a monitoring service for various torrent clients
home: https://truecharts.org/charts/stable/flood
icon: https://truecharts.org/img/hotlink-ok/chart-icons/flood.png
keywords:
  - flood
  - rtorrent
  - qbittorrent
  - transmission
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: flood
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/flood
  - https://github.com/jesec/flood
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
