apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: webNUT (UPS network monitoring web ui).
home: https://truecharts.org/charts/stable/webnut
icon: https://truecharts.org/img/hotlink-ok/chart-icons/webnut.png
keywords:
  - webnut
  - ups
  - monitoring
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: webnut
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/webnut
  - https://github.com/rshipp/webNUT
type: application
version: 5.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: monitoring
  truecharts.org/SCALE-support: "true"
