apiVersion: v2
appVersion: "0.44.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Scrypted is a high performance home video integration and automation platform.
home: https://truecharts.org/charts/incubator/scrypted
icon: https://truecharts.org/img/hotlink-ok/chart-icons/scrypted.png
keywords:
  - scrypted
  - automation
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: scrypted
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/scrypted
  - https://github.com/koush/scrypted
type: application
version: 1.0.7
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
