apiVersion: v2
appVersion: "2.0.35"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 9.0.43
description: Kimai is a free, open source and online time-tracking software designed for small businesses and freelancers.
home: https://truecharts.org/charts/incubator/kimai
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kimai.png
keywords:
  - kimai
  - time
  - tracking
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: kimai
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/kimai
  - https://github.com/kevinpapst/kimai2
  - https://github.com/tobybatch/kimai2
version: 8.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: productivity
  truecharts.org/SCALE-support: "true"
