apiVersion: v2
appVersion: "2.0.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: clickhouse.enabled
    name: clickhouse
    repository: https://deps.truecharts.org/
    version: 7.0.30
deprecated: false
description: Plausible is lightweight and open source web analytics. No cookies and fully compliant with GDPR, CCPA and PECR.
home: https://truecharts.org/charts/stable/plausible
icon: https://truecharts.org/img/hotlink-ok/chart-icons/plausible.png
keywords:
  - plausible
  - analytics
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: plausible
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/plausible
  - https://plausible.io/
  - https://plausible.io/docs/self-hosting
  - https://github.com/plausible/analytics
  - https://github.com/plausible/hosting
type: application
version: 5.0.13
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: analytics
  truecharts.org/SCALE-support: "true"
