apiVersion: v2
appVersion: "9.0.4"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: the self-hosted gaming platform for alternatively obtained games.
home: https://truecharts.org/charts/stable/gamevault-backend
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gamevault-backend.png
keywords:
  - gamevault-backend
  - games
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: gamevault-backend
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/gamevault-backend
  - https://github.com/Phalcode/gamevault-backend
type: application
version: 1.1.23
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: games
  truecharts.org/SCALE-support: "true"
