apiVersion: v2
appVersion: "1.21.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Open source, self-hostable watched list
home: https://truecharts.org/charts/stable/watcharr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/watcharr.png
keywords:
  - watcharr
  - media
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: watcharr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/watcharr
  - https://github.com/sbondCo/Watcharr
type: application
version: 1.1.1
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
