apiVersion: v2
appVersion: "0.107.41"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Free and open source, powerful network-wide ads & trackers blocking DNS server.
home: https://truecharts.org/charts/stable/adguard-home
icon: https://truecharts.org/img/hotlink-ok/chart-icons/adguard-home.png
keywords:
  - adblock
  - adguard
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: adguard-home
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/adguard-home
version: 6.0.14
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
