apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: kavita
version: 6.0.11
appVersion: "0.7.8"
description: Kavita is a rocket fueled self-hosted digital library which supports a vast array of file formats
type: application
deprecated: false
home: https://truecharts.org/charts/stable/kavita
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kavita.png
keywords:
  - kavita
  - manga
  - library
  - book
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/kavita
  - https://www.kavitareader.com
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
    # condition:
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
