apiVersion: v2
appVersion: "0.10.4"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Gaps searches through your Plex Server or local folders for all movies, then queries for known movies in the same collection.
home: https://truecharts.org/charts/stable/gaps
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gaps.png
keywords:
  - gaps
  - plex
  - plex-media-server
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: gaps
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/gaps
  - https://github.com/JasonHHouse/gaps
type: application
version: 15.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
