apiVersion: v2
appVersion: "10.6.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Airsonic is a Free and Open Source community driven media server
home: https://truecharts.org/charts/stable/airsonic
icon: https://truecharts.org/img/hotlink-ok/chart-icons/airsonic.png
keywords:
  - airsonic
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: airsonic
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/airsonic
  - https://github.com/airsonic/airsonic
  - https://github.com/linuxserver/docker-airsonic
  - https://github.com/k8s-at-home/charts/tree/master/charts/airsonic
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
