apiVersion: v2
appVersion: "2.0.18"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Eclipse Mosquitto - An open source MQTT broker
home: https://truecharts.org/charts/stable/mosquitto
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mosquitto.png
keywords:
  - mosquitto
  - MQTT
  - eclipse-iot
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: mosquitto
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/mosquitto
  - https://github.com/eclipse/mosquitto
type: application
version: 11.0.15
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: homeautomation
  truecharts.org/SCALE-support: "true"
