apiVersion: v2
appVersion: "5.2.3"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: dash. (or dashdot) is a modern server dashboard, running on the latest tech, designed with glassmorphism in mind.
home: https://truecharts.org/charts/stable/dashdot
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dashdot.png
keywords:
  - dashboard
  - dashdot
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: dashdot
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/dashdot
  - https://github.com/MauriceNino/dashdot
version: 5.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
