apiVersion: v2
appVersion: "0.21.1155"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Advanced tool to create your own TrueCharts-based App
home: https://truecharts.org/charts/stable/custom-app
icon: https://truecharts.org/img/hotlink-ok/chart-icons/custom-app.png
keywords:
  - custom
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: custom-app
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/custom-app
type: application
version: 9.0.47
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: custom
  truecharts.org/SCALE-support: "true"
