apiVersion: v2
appVersion: "2.0.4.3802"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Looks and smells like Sonarr but made for music
home: https://truecharts.org/charts/stable/lidarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lidarr.png
keywords:
  - lidarr
  - torrent
  - usenet
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: lidarr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/lidarr
  - https://github.com/Lidarr/Lidarr
type: application
version: 17.0.26
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
