apiVersion: v2
appVersion: "edge-latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Airsonic is a Free and Open Source community driven media server
home: https://truecharts.org/charts/stable/airsonic-advanced
icon: https://truecharts.org/img/hotlink-ok/chart-icons/airsonic-advanced.png
keywords:
  - airsonic
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: airsonic-advanced
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/airsonic-advanced
  - https://github.com/airsonic/airsonic-advanced
version: 10.0.10
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
