apiVersion: v2
appVersion: "4.2.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Anime cataloging program designed to automate the cataloging of your collection.
home: https://truecharts.org/charts/stable/shoko-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/shoko-server.png
keywords:
  - shoko-server
  - Tools-Utilities
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: shoko-server
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/shoko-server
  - https://github.com/ShokoAnime/ShokoServer
type: application
version: 6.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
