apiVersion: v2
appVersion: "6.0.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A high-performance, enterprise-grade system for backing up Linux, Windows and macOS PCs and laptops to a server's disk.
home: https://truecharts.org/charts/incubator/backuppc
icon: https://truecharts.org/img/hotlink-ok/chart-icons/backuppc.png
keywords:
  - backuppc
  - Backup
  - Network-Web
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: backuppc
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/backuppc
  - https://github.com/tiredofit/docker-backuppc
  - https://backuppc.github.io/backuppc/index.html
type: application
version: 3.0.7
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: Backup
  truecharts.org/SCALE-support: "true"
