apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Open source alternative front-end to YouTube.
home: https://truecharts.org/charts/stable/invidious
icon: https://truecharts.org/img/hotlink-ok/chart-icons/invidious.png
keywords:
  - invidious
  - youtube
  - media
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: invidious
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/invidious
  - https://github.com/iv-org/invidious
  - https://docs.invidious.io/installation/#docker
version: 6.0.23
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
