apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: zerotier
version: 6.0.12
appVersion: "1.12.2"
description: ZeroTier is a smart programmable Ethernet switch for planet Earth
type: application
deprecated: false
home: https://truecharts.org/charts/stable/zerotier
icon: https://truecharts.org/img/hotlink-ok/chart-icons/zerotier.png
keywords:
  - zerotier
  - network
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/zerotier
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: network
  truecharts.org/SCALE-support: "true"
