apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Docusaurus makes it easy to maintain Open Source documentation websites.
home: https://truecharts.org/charts/stable/docusaurus
icon: https://truecharts.org/img/hotlink-ok/chart-icons/docusaurus.png
keywords:
  - documentation
  - website
  - Docusaurus
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: docusaurus
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/docusaurus
  - https://github.com/awesometic/docker-docusaurus
type: application
version: 5.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: website
  truecharts.org/SCALE-support: "true"
