apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A custom SteamCMD chart that runs Sons Of The Forest Server.
home: https://truecharts.org/charts/incubator/sonsoftheforest
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sonsoftheforest.png
keywords:
  - sonsoftheforest
  - GameServers
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: sonsoftheforest
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/sonsoftheforest
  - https://github.com/ich777/docker-steamcmd-server/tree/sonsoftheforest
type: application
version: 0.0.9
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: GameServers
  truecharts.org/SCALE-support: "true"
