apiVersion: v2
appVersion: "1.32.7.7621"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Plex Media Server
home: https://truecharts.org/charts/stable/plex
icon: https://truecharts.org/img/hotlink-ok/chart-icons/plex.png
keywords:
  - plex
  - plex-media-server
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: plex
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/plex
  - https://github.com/k8s-at-home/container-images/pkgs/container/plex
type: application
version: 14.1.3
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
