apiVersion: v2
appVersion: "23.11.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: FileBot is the ultimate tool for organizing and renaming your movies, tv shows or anime, and music well as downloading subtitles and artwork. It's smart and just works.
home: https://truecharts.org/charts/stable/filebot
icon: https://truecharts.org/img/hotlink-ok/chart-icons/filebot.png
keywords:
  - media
  - filebot
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: filebot
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/filebot
  - https://github.com/jlesage/docker-filebot
type: application
version: 5.0.11
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
