apiVersion: v2
appVersion: "0.3.38"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A superlight rust written social server.
home: https://truecharts.org/charts/incubator/vocechat-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/vocechat-server.png
keywords:
  - vocechat-server
  - social
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: vocechat-server
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/vocechat-server
  - https://github.com/Privoce/vocechat-server-rust
type: application
version: 0.0.8
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: social
  truecharts.org/SCALE-support: "true"
