apiVersion: v2
appVersion: "0.69.1"
deprecated: false
description: Prometheus Operator is an operator for prometheus
home: https://truecharts.org/charts/operators/prometheus-operator
icon: https://truecharts.org/img/hotlink-ok/chart-icons/prometheus-operator.png
keywords:
  - operator
  - prometheus
  - metics
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 15.3.1
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: prometheus-operator
sources:
  - https://github.com/truecharts/charts/tree/master/charts/operators/prometheus-operator
  - https://github.com/prometheus-operator
type: application
version: 2.0.0
annotations:
  truecharts.org/category: operators
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
