apiVersion: v2
appVersion: "1.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: A dead simple URL shortener.
home: https://truecharts.org/charts/stable/simply-shorten
icon: https://truecharts.org/img/hotlink-ok/chart-icons/simply-shorten.png
keywords:
  - simply-shorten
  - Cloud
  - Productivity
  - Network-Web
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: simply-shorten
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/simply-shorten
  - https://gitlab.com/draganczukp/simply-shorten
type: application
version: 5.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: Cloud
  truecharts.org/SCALE-support: "true"
