apiVersion: v2
appVersion: "2.1.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A borg Backup server
home: https://truecharts.org/charts/stable/borg-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/borg-server.png
keywords:
  - borg-server
  - backup
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: borg-server
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/borg-server
  - https://github.com/AnotherStranger/docker-borg-backup
type: application
version: 1.0.1
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: backup
  truecharts.org/SCALE-support: "true"
