apiVersion: v2
appVersion: latest
deprecated: false
description: CloudNativePG is a clustered postgresql database operator
home: https://truecharts.org/charts/operators/cloudnative-pg
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cloudnative-pg.png
keywords:
  - database
  - cloudnative-pg
  - cnpg
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.3.5
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.19.1
    alias: cloudnative-pg
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: cloudnative-pg
sources:
  - https://github.com/truecharts/charts/tree/master/charts/operators/cloudnative-pg
  - https://github.com/cloudnative-pg
  - https://cloudnative-pg.io/
type: application
version: 3.0.1
annotations:
  truecharts.org/category: operators
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
