apiVersion: v2
appVersion: "0.1.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Take control over your live stream video by running it yourself. Streaming + chat out of the box.
home: https://truecharts.org/charts/stable/owncast
icon: https://truecharts.org/img/hotlink-ok/chart-icons/owncast.png
keywords:
  - owncast
  - stream
  - open source
  - chat
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: owncast
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/owncast
  - https://owncast.online/
  - https://github.com/owncast/owncast
version: 10.0.11
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
