apiVersion: v2
appVersion: "1.23.7"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A fancy self-hosted monitoring tool
home: https://truecharts.org/charts/stable/uptime-kuma
icon: https://truecharts.org/img/hotlink-ok/chart-icons/uptime-kuma.png
keywords:
  - monitoring
  - uptime
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: uptime-kuma
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/uptime-kuma
  - https://github.com/louislam/uptime-kuma
type: application
version: 7.0.18
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: monitoring
  truecharts.org/SCALE-support: "true"
