apiVersion: v2
appVersion: "0.16.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Music streaming server / subsonic server API implementation
home: https://truecharts.org/charts/stable/gonic
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gonic.png
keywords:
  - music
  - subsonic
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: gonic
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/gonic
  - https://github.com/sentriz/gonic
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
