apiVersion: v2
appVersion: 1.8.3
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: A comics/mangas server to serve/stream pages via API
home: https://truecharts.org/charts/stable/komga
icon: https://truecharts.org/img/hotlink-ok/chart-icons/komga.png
keywords:
  - komga
  - comics
  - mangas
  - server
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: komga
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/komga
  - https://komga.org/
  - https://github.com/gotson/komga
version: 10.1.1
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
