apiVersion: v2
appVersion: 1.4.0
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements
home: https://truecharts.org/charts/stable/bazarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/bazarr.png
keywords:
  - bazarr
  - radarr
  - sonarr
  - subtitles
  - usenet
  - torrent
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: bazarr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/bazarr
  - https://github.com/morpheus65535/bazarr
type: application
version: 15.1.1
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
