apiVersion: v2
appVersion: "1.1.14"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: A cross-platform Anki sync server.
home: https://truecharts.org/charts/incubator/anki-sync-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/anki-sync-server.png
keywords:
  - anki-sync-server
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: anki-sync-server
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/anki-sync-server
  - https://github.com/ankicommunity/anki-devops-services
version: 3.0.6
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
