apiVersion: v2
appVersion: "2.5.300"
description: Make documentation a joy to write using Wiki.js's beautiful and intuitive interface!
name: wikijs
version: 12.0.11
kubeVersion: ">=1.16.0-0"
keywords:
  - wiki
  - wikijs
home: https://truecharts.org/charts/stable/wikijs
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wikijs.png
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/wikijs
  - https://docs.requarks.io/install/docker
  - https://github.com/Requarks/wiki
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
