apiVersion: v2
appVersion: "2.4.3"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A self-hosted midwestern Discord music bot that doesn't suck.
home: https://truecharts.org/charts/stable/muse
icon: https://truecharts.org/img/hotlink-ok/chart-icons/muse.png
keywords:
  - muse
  - media
  - discord-bot
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: muse
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/muse
  - https://github.com/codetheweb/muse
type: application
version: 2.0.13
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
