apiVersion: v2
appVersion: "0.14.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A multi-platform media downloader that indexes and downloads content from your accessible Plex servers.
home: https://truecharts.org/charts/stable/plexripper
icon: https://truecharts.org/img/hotlink-ok/chart-icons/plexripper.png
keywords:
  - plexripper
  - Backup
  - Downloaders
  - MediaApp-Video
  - MediaApp-Music
  - MediaApp-Photos
  - MediaApp-Other
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: plexripper
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/plexripper
  - https://github.com/PlexRipper/PlexRipper/
type: application
version: 5.0.5
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
