apiVersion: v2
appVersion: "23.10.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Actual is a super fast privacy-focused app for managing your finances.
home: https://truecharts.org/charts/stable/actualserver
icon: https://truecharts.org/img/hotlink-ok/chart-icons/actualserver.png
keywords:
  - actualserver
  - finance
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: actualserver
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/actualserver
  - https://github.com/Kippenhof/docker-templates
type: application
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: finance
version: 5.0.14
