apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A Lidarr companion script to automatically download music for Lidarr.
home: https://truecharts.org/charts/stable/automatic-music-downloader
icon: https://truecharts.org/img/hotlink-ok/chart-icons/automatic-music-downloader.png
keywords:
  - automatic
  - music
  - downloader
  - deemix
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: automatic-music-downloader
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/automatic-music-downloader
  - https://github.com/RandomNinjaAtk/docker-amd
type: application
version: 6.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
