apiVersion: v2
appVersion: "2023.11.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Minecraft Java Dedicated Server
home: https://truecharts.org/charts/stable/minecraft-java
icon: https://truecharts.org/img/hotlink-ok/chart-icons/minecraft-java.png
keywords:
  - minecraft-java
  - minecraft
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: minecraft-java
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/minecraft-java
  - https://github.com/itzg/docker-minecraft-server
type: application
version: 5.1.3
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: games
  truecharts.org/SCALE-support: "true"
