apiVersion: v2
appVersion: "4.37.5"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 15.3.1
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 9.0.0
deprecated: false
description: Authelia is a Single Sign-On Multi-Factor portal for web apps
home: https://truecharts.org/charts/enterprise/authelia
icon: https://truecharts.org/img/hotlink-ok/chart-icons/authelia.png
keywords:
  - authelia
  - authentication
  - login
  - SSO
  - Authentication
  - Security
  - Two-Factor
  - U2F
  - YubiKey
  - Push Notifications
  - LDAP
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: authelia
sources:
  - https://github.com/truecharts/charts/tree/master/charts/enterprise/authelia
  - https://github.com/authelia/chartrepo
  - https://github.com/authelia/authelia
type: application
version: 20.0.0
annotations:
  truecharts.org/category: security
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
