apiVersion: v2
appVersion: "1.54.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Tailscale lets you connect your devices and users together in your own secure virtual private network
home: https://truecharts.org/charts/stable/tailscale
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tailscale.png
keywords:
  - vpn
  - tailscale
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: tailscale
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/tailscale
  - https://github.com/tailscale/tailscale/blob/main/docs/k8s/run.sh
version: 5.1.18
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: network
  truecharts.org/SCALE-support: "true"
