apiVersion: v2
appVersion: "5.12"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Omada is a SDN tool for TP-Link Omada hardware
home: https://truecharts.org/charts/stable/omada-controller
icon: https://truecharts.org/img/hotlink-ok/chart-icons/omada-controller.png
keywords:
  - omada-controller
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: omada-controller
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/omada-controller
  - https://github.com/mbentley/docker-omada-controller
version: 10.0.35
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
