apiVersion: v2
appVersion: "1.3.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Server for Ferdi that you can re-use to run your own
home: https://truecharts.org/charts/stable/ferdi-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ferdi-server.png
keywords:
  - ferdi
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: ferdi-server
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/ferdi-server
  - https://github.com/getferdi/server
version: 8.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
