apiVersion: v2
appVersion: 4.16.0
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 9.0.43
description: Matomo is the leading Free/Libre open analytics platform
home: https://truecharts.org/charts/stable/matomo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/matomo.png
keywords:
  - analytics
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: matomo
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/matomo
  - https://github.com/bitnami/bitnami-docker-matomo
  - https://github.com/matomo-org/matomo
version: 8.1.1
annotations:
  truecharts.org/category: productivity
  truecharts.org/SCALE-support: "true"
