apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Store securely encrypted backups on cloud storage services!
home: https://truecharts.org/charts/stable/duplicati
icon: https://truecharts.org/img/hotlink-ok/chart-icons/duplicati.png
keywords:
  - duplicati
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: duplicati
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/duplicati
  - https://github.com/duplicati/duplicati
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
