apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: deemix is a deezer downloader built from the ashes of Deezloader Remix.
home: https://truecharts.org/charts/stable/deemix
icon: https://truecharts.org/img/hotlink-ok/chart-icons/deemix.png
keywords:
  - music
  - deemix
  - deezer
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: deemix
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/deemix
  - https://gitlab.com/Bockiii/deemix-docker.git
  - https://git.freezerapp.xyz/RemixDev/deemix-py
type: application
version: 7.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
