apiVersion: v2
appVersion: "5.8.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A server software for Minecraft Bedrock Edition in PHP.
home: https://truecharts.org/charts/incubator/pocketmine-mp
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pocketmine-mp.png
keywords:
  - pocketmine-mp
  - minecraft
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: pocketmine-mp
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/pocketmine-mp
  - https://github.com/pmmp/PocketMine-MP
type: application
version: 0.0.2
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: games
  truecharts.org/SCALE-support: "true"
