apiVersion: v2
appVersion: latest
deprecated: false
description: A network load-balancer implementation for Kubernetes using standard routing protocols
home: https://truecharts.org/charts/operators/metallb
icon: https://truecharts.org/img/hotlink-ok/chart-icons/metallb.png
keywords:
  - metallb
  - loadbalancer
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.3.5
  - name: metallb
    repository: https://metallb.github.io/metallb
    version: 0.13.12
    alias: metallb
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: metallb
sources:
  - https://github.com/truecharts/charts/tree/master/charts/operators/metallb
  - https://github.com/metallb/metallb
  - https://metallb.universe.tf
type: application
version: 11.0.1
annotations:
  truecharts.org/category: operators
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
