apiVersion: v2
appVersion: 0.62.3
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Trilium Notes is a hierarchical note taking application with focus on building large personal knowledge bases.
home: https://truecharts.org/charts/stable/trilium-notes
icon: https://truecharts.org/img/hotlink-ok/chart-icons/trilium-notes.png
keywords:
  - trilium
  - notes
  - note
  - information
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: trilium-notes
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/trilium-notes
  - https://github.com/zadam/trilium
type: application
version: 9.1.2
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
