apiVersion: v2
appVersion: "2.2.0.200"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: M3U Proxy for Plex DVR and Emby Live TV.
home: https://truecharts.org/charts/stable/xteve
icon: https://truecharts.org/img/hotlink-ok/chart-icons/xteve.png
keywords:
  - xteve
  - iptv
  - plex
  - emby
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: xteve
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/xteve
  - https://github.com/xteve-project/xTeVe
  - https://github.com/k8s-at-home/container-images
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
