apiVersion: v2
appVersion: "1.21.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.66
description: Baserow is an open source no-code database tool and Airtable alternative.
home: https://truecharts.org/charts/stable/baserow
icon: https://truecharts.org/img/hotlink-ok/chart-icons/baserow.png
keywords:
  - baserow
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: baserow
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/baserow
  - https://gitlab.com/bramw/baserow/
version: 8.0.13
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: productivity
  truecharts.org/SCALE-support: "true"
