apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.66
deprecated: false
description: A free and open source alternative Twitter front-end focused on privacy and performance.
home: https://truecharts.org/charts/incubator/nitter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nitter.png
keywords:
  - nitter
  - libre
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: nitter
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/nitter
  - https://github.com/zedeus/nitter
type: application
version: 2.0.1
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
