apiVersion: v2
appVersion: "1.6.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 7.0.6
deprecated: false
description: A self-hosted manga downloader.
home: https://truecharts.org/charts/incubator/kaizoku
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kaizoku.png
keywords:
  - kaizoku
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: kaizoku
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/kaizoku
  - https://github.com/oae/kaizoku
type: application
version: 0.1.7
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
