apiVersion: v2
appVersion: 3.8.8
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A simple script to monitor qBit and communicate with Radarr and Sonarr.
home: https://truecharts.org/charts/stable/qbitrr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/qbitrr.png
keywords:
  - qbitrr
  - Downloaders
  - MediaApp-Other
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: qbitrr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/qbitrr
  - https://github.com/Feramance/Qbitrr
type: application
version: 0.0.28
annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Downloaders
