apiVersion: v2
appVersion: 2.6.0
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Audiobookshelf is a self-hosted audiobook server for managing and playing your audiobooks.
home: https://truecharts.org/charts/stable/audiobookshelf
icon: https://truecharts.org/img/hotlink-ok/chart-icons/audiobookshelf.png
keywords:
  - audiobookshelf
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: audiobookshelf
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/audiobookshelf
  - https://github.com/advplyr/audiobookshelf
version: 6.1.1
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
