apiVersion: v2
appVersion: "2.15.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: A discord bot that monitors your game server and tracks the live data of your game servers.
home: https://truecharts.org/charts/stable/discordgsm
icon: https://truecharts.org/img/hotlink-ok/chart-icons/discordgsm.png
keywords:
  - discordgsm
  - game-server
  - monitor
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: discordgsm
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/discordgsm
  - https://github.com/DiscordGSM/GameServerMonitor
version: 4.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: monitor
  truecharts.org/SCALE-support: "true"
