apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: pwndrop
version: 6.0.23
appVersion: "1.0.1"
description: Pwndrop is a self-deployable file hosting service for sending out red teaming payloads or securely sharing your private files over HTTP and WebDAV.
type: application
deprecated: false
home: https://truecharts.org/charts/stable/pwndrop
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pwndrop.png
keywords:
  - pwndrop
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/pwndrop
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
    # condition:
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: incubator
  truecharts.org/SCALE-support: "true"
