apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A Dropbox-like file manager that let you manage your data anywhere it is located.
home: https://truecharts.org/charts/incubator/filestash
icon: https://truecharts.org/img/hotlink-ok/chart-icons/filestash.png
keywords:
  - filestash
  - Cloud
  - Productivity
  - Network-Web
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: filestash
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/filestash
  - https://github.com/mickael-kerjean/filestash
  - https://www.filestash.app/
type: application
version: 3.0.6
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: Cloud
  truecharts.org/SCALE-support: "true"
