apiVersion: v2
appVersion: "2.48.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: exporters.enabled,exporters.node-exporter.enabled
    name: node-exporter
    repository: https://deps.truecharts.org
    version: 3.0.43
  - condition: exporters.enabled,exporters.kube-state-metrics.enabled
    name: kube-state-metrics
    repository: https://deps.truecharts.org
    version: 3.0.41
deprecated: false
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
icon: https://truecharts.org/img/hotlink-ok/chart-icons/prometheus.png
home: https://truecharts.org/charts/enterprise/prometheus
keywords:
  - metrics
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: prometheus
sources:
  - https://github.com/truecharts/charts/tree/master/charts/enterprise/prometheus
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
type: application
version: 13.0.23
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: metrics
  truecharts.org/SCALE-support: "true"
