apiVersion: v2
appVersion: "2.5.5"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: "Fully featured and highly configurable SFTP server with optional HTTP/S, FTP, FTPS and WebDAV support. Several storage backends are supported: local filesystem, encrypted local filesystem, S3 (compatible) Object Storage, Google Cloud Storage, Azure Blob Storage, SFTP."
home: https://truecharts.org/charts/stable/sftpgo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sftpgo.png
keywords:
  - sftpgo
  - Network-FTP
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: sftpgo
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/sftpgo
  - https://github.com/drakkan/sftpgo
type: application
version: 3.0.17
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Network-FTP
