apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: synclounge
version: 6.0.23
appVersion: 5.2.23
description: Synclounge is a third party tool that allows you to watch Plex in sync with your friends/family, wherever you are.
type: application
deprecated: false
home: https://truecharts.org/charts/stable/synclounge
icon: https://truecharts.org/img/hotlink-ok/chart-icons/synclounge.png
keywords:
  - synclounge
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/synclounge
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
    # condition:
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
