apiVersion: v2
appVersion: "4.3.14"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: TinyMediaManager is a full featured media manager to organize and clean up your media library.
home: https://truecharts.org/charts/stable/tinymediamanager
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tinymediamanager.png
keywords:
  - tiny
  - media
  - manager
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: tinymediamanager
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/tinymediamanager
  - https://gitlab.com/tinyMediaManager/tinyMediaManager
version: 6.0.12
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
