apiVersion: v2
appVersion: "2023.10.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Client for Cloudflare Tunnel, a daemon that exposes private services through the Cloudflare edge.
home: https://truecharts.org/charts/stable/cloudflared
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cloudflared.png
keywords:
  - cloudflared
  - networking
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: cloudflared
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/cloudflared
type: application
version: 6.0.15
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: network
  truecharts.org/SCALE-support: "true"
