apiVersion: v2
appVersion: "1.21.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: memcached.enabled
    name: memcached
    repository: https://deps.truecharts.org/
    version: 6.0.77
deprecated: false
description: Self hosted GIT repositories
home: https://truecharts.org/charts/stable/gitea
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gitea.png
keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - gitea
  - gogs
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: gitea
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/gitea
  - https://gitea.com/gitea/helm-chart
  - https://github.com/go-gitea/gitea
type: application
version: 14.0.14
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: GIT
  truecharts.org/SCALE-support: "true"
