apiVersion: v2
appVersion: "2.0.49"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: This is a web interface to manage your torrents on Real-Debrid, AllDebrid or Premiumize.
home: https://truecharts.org/charts/stable/rdtclient
icon: https://truecharts.org/img/hotlink-ok/chart-icons/rdtclient.png
keywords:
  - rdtclient
  - torrent
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: rdtclient
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/rdtclient
  - https://github.com/rogerfar/rdt-client
type: application
version: 1.0.2
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
