apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Generate a full web-page screenshot with our service, that provides rich interface to make any kind of web screenshots online for free with no limits. The simplest way to take a full page screenshot.
home: https://truecharts.org/charts/stable/website-shot
icon: https://truecharts.org/img/hotlink-ok/chart-icons/website-shot.png
keywords:
  - website-shot
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: website-shot
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/website-shot
  - https://github.com/Flowko/website-shot
version: 7.0.7
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
