apiVersion: v2
appVersion: "2.10.5"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Traefik is a flexible reverse proxy and Ingress Provider.
home: https://truecharts.org/charts/enterprise/traefik
icon: https://truecharts.org/img/hotlink-ok/chart-icons/traefik.png
keywords:
  - traefik
  - ingress
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: traefik
sources:
  - https://github.com/truecharts/charts/tree/master/charts/enterprise/traefik
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
  - https://traefik.io/
type: application
version: 22.1.1
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: network
  truecharts.org/SCALE-support: "true"
