apiVersion: v2
appVersion: "360b2295"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: pyLoad is a Free and Open Source download manager written in Python and designed to be extremely lightweight, easily extensible and fully manageable via web.
home: https://truecharts.org/charts/stable/pyload
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pyload.png
keywords:
  - pyload
  - download
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: pyload
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/pyload
  - https://github.com/pyload/pyload
version: 10.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
