apiVersion: v2
appVersion: 8.0
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.3.5
deprecated: false
description: Web-Based postgresql database management utility
home: https://truecharts.org/charts/stable/pgadmin
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pgadmin.png
keywords:
  - pgadmin
  - db
  - database
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: pgadmin
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/pgadmin
  - https://www.pgadmin.org/
type: application
version: 12.0.0
annotations:
  truecharts.org/category: management
  truecharts.org/SCALE-support: "true"
