image:
  repository: dpage/pgadmin4
  pullPolicy: IfNotPresent
  tag: 8.0@sha256:2f162ef35d3afca1396c4222a0403eb861b9800039bcf368074fd19ff02b8cd8
service:
  main:
    ports:
      main:
        port: 10024
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/var/lib/pgadmin"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: true
    readOnlyRootFilesystem: false
    runAsUser: 5050
    runAsGroup: 5050
    fsGroup: 5050
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: http
              path: /misc/ping
            readiness:
              enabled: true
              type: http
              path: /misc/ping
            startup:
              enabled: true
              type: http
              path: /misc/ping
          env:
            PGADMIN_DEFAULT_EMAIL: "replace@this.now"
            PGADMIN_DEFAULT_PASSWORD: "changeme"
