apiVersion: v2
appVersion: "1.7.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A new generation cross-platform cloud backup tool.
home: https://truecharts.org/charts/stable/duplicacy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/duplicacy.png
keywords:
  - duplicacy
  - Backup
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: duplicacy
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/duplicacy
  - https://hotio.dev/containers/duplicacy
type: application
version: 3.0.2
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: Backup
  truecharts.org/SCALE-support: "true"
