apiVersion: v2
appVersion: "2.8.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: ntfy is a simple HTTP-based pub-sub notification service. It allows you to send notifications to your phone or desktop via scripts from any computer.
home: https://truecharts.org/charts/stable/ntfy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ntfy.png
keywords:
  - ntfy
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: ntfy
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/ntfy
  - https://github.com/binwiederhier/ntfy/
version: 6.1.1
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
