apiVersion: v2
appVersion: "1.0.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Mealie is a self hosted recipe manager and meal planner with a RestAPI backend
home: https://truecharts.org/charts/stable/mealie
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mealie.png
keywords:
  - grocy
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: mealie
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/mealie
  - https://github.com/mealie-recipes/mealie
version: 18.0.3
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: utilities
  truecharts.org/SCALE-support: "true"
