apiVersion: v2
appVersion: "7.1.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Calibre is a powerful and easy to use e-book manager.
home: https://truecharts.org/charts/stable/calibre
icon: https://truecharts.org/img/hotlink-ok/chart-icons/calibre.png
keywords:
  - calibre
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: calibre
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/calibre
  - https://github.com/kovidgoyal/calibre/
version: 11.1.36
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
