apiVersion: v2
appVersion: "7.8.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: Professional Photo Management with the Power of Open Source
home: https://truecharts.org/charts/stable/digikam
icon: https://truecharts.org/img/hotlink-ok/chart-icons/digikam.png
keywords:
  - digikam
  - photo
  - management
  - image
  - gallery
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: digikam
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/digikam
  - https://github.com/linuxserver/docker-digikam
  - https://www.digikam.org/
type: application
version: 8.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
