apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: "Synchronized video viewing with chat and other features. Lightweight modern implementation and very easy way to run locally."
home: https://truecharts.org/charts/stable/synctube
icon: https://truecharts.org/img/hotlink-ok/chart-icons/synctube.png
keywords:
  - synctube
  - Cloud
  - Productivity
  - Tools-Utilities
  - MediaApp-Video
  - MediaServer-Video
  - Network-Web
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: synctube
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/synctube
  - https://github.com/RblSb/SyncTube
type: application
version: 4.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Cloud
