apiVersion: v2
appVersion: "1.3.25"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: Plex to AniList Sync.
home: https://truecharts.org/charts/stable/plexanisync
icon: https://truecharts.org/img/hotlink-ok/chart-icons/plexanisync.png
keywords:
  - plexanisync
  - media
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: plexanisync
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/plexanisync
  - https://github.com/RickDB/PlexAniSync
  - https://github.com/RickDB/PlexAniSync/pkgs/container/plexanisync
type: application
version: 3.0.14
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
