apiVersion: v2
appVersion: "7.5.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 8.0.47
description: "ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts, spreadsheets and presentations, fully compatible with Office Open XML formats: .docx, .xlsx, .pptx and enabling collaborative editing in real time."
home: https://truecharts.org/charts/stable/onlyoffice-document-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/onlyoffice-document-server.png
keywords:
  - onlyoffice
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: onlyoffice-document-server
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/onlyoffice-document-server
  - https://github.com/ONLYOFFICE/DocumentServer
  - https://github.com/ONLYOFFICE/Docker-DocumentServer
version: 12.0.11
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: office
  truecharts.org/SCALE-support: "true"
