apiVersion: v2
appVersion: "6.0.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A command-line application that will automatically synchronize recommended settings from TRaSH guides to your Sonarr/Radarr instances.
home: https://truecharts.org/charts/stable/recyclarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/recyclarr.png
keywords:
  - recyclarr
  - Tools-Utilities
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: recyclarr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/recyclarr
  - https://github.com/recyclarr/recyclarr
  - https://github.com/recyclarr/recyclarr/pkgs/container/recyclarr
type: application
version: 6.0.18
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Tools-Utilities
