apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: A discord bot that allows you to play old nintendo games with your friends over chat.
home: https://truecharts.org/charts/stable/retrobot
icon: https://truecharts.org/img/hotlink-ok/chart-icons/retrobot.png
keywords:
  - retrobot
  - emulator
  - discord
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: retrobot
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/retrobot
  - https://github.com/rossimo/retrobot
type: application
version: 5.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: emulator
  truecharts.org/SCALE-support: "true"
