apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
deprecated: false
description: DNS Chart service for a steam cache.
home: https://truecharts.org/charts/stable/lancache-dns
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lancache-dns.png
keywords:
  - lancache-dns
  - dns
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: lancache-dns
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/lancache-dns
  - https://github.com/lancachenet/lancache-dns
type: application
version: 5.0.10
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: networking
  truecharts.org/SCALE-support: "true"
