apiVersion: v2
appVersion: "3.5.4"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: ProtonMail IMAP/SMTP Bridge to work on the network.
home: https://truecharts.org/charts/stable/protonmail-bridge
icon: https://truecharts.org/img/hotlink-ok/chart-icons/protonmail-bridge.png
keywords:
  - protonmail
  - protonmail-bridge
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: protonmail-bridge
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/protonmail-bridge
  - https://github.com/shenxn/protonmail-bridge-docker
version: 11.0.13
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
