apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: guacd
version: 6.0.11
appVersion: "1.5.3"
description: Guacd - Apache Guacamole is a clientless remote desktop gateway.
type: application
deprecated: false
home: https://truecharts.org/charts/stable/guacd
icon: https://truecharts.org/img/hotlink-ok/chart-icons/guacd.png
keywords:
  - guacd
  - guacamole
  - remote
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/guacd
  - https://github.com/apache/guacamole-server
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
    # condition:
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  min_scale_version: "22.12.4"
  max_scale_version: "23.10.1"
  truecharts.org/category: incubator
  truecharts.org/SCALE-support: "true"
