apiVersion: v2
appVersion: 2023.6.27
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.5.0
description: An Automatic Video Library Manager for TV Shows
home: https://truecharts.org/charts/stable/sickchill
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sickchill.png
keywords:
  - sickchill
  - video
  - library
  - manager
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: sickchill
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/sickchill
  - https://github.com/linuxserver/docker-sickchill
  - https://github.com/SickChill/SickChill
type: application
version: 7.0.28
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
